LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# ==============================================
# Node.js 统计任务（每5分钟轮流执行，3个脚本间隔5分钟）
# ==============================================

# daily-stats.js: 每小时的 0,15,30,45 分钟执行（统计当天）
0,15,30,45 * * * * cd /data/scripts && /root/.nvm/versions/node/v20.19.5/bin/node daily-stats.js $(date +\%Y-\%m-\%d)>> /data/logs/daily-stats-$(date +\%Y-\%m-\%d).log 2>&1

# daily-stats.js: 凌晨 1:00 重新统计前一天的完整数据
0 8 * * * cd /data/scripts && /root/.nvm/versions/node/v20.19.5/bin/node daily-stats.js $(date -d "yesterday" +\%Y-\%m-\%d)>> /data/logs/daily-stats-$(date -d "yesterday" +\%Y-\%m-\%d).log 2>&1

# ltv-stats.js: 每小时的 5,20,35,50 分钟执行
5,20,35,50 * * * * cd /data/scripts && /root/.nvm/versions/node/v20.19.5/bin/node ltv-stats.js $(date +\%Y-\%m-\%d)>> /data/logs/ltv-stats.log 2>&1

# ltv-stats.js: 凌晨 1:05 重新统计前一天的完整 LTV 数据
5 10 * * * cd /data/scripts && /root/.nvm/versions/node/v20.19.5/bin/node ltv-stats.js $(date -d "yesterday" +\%Y-\%m-\%d)>> /data/logs/ltv-stats.log 2>&1

# auto-gift-delivery.js: 每小时的 10,25,40,55 分钟执行
*/30 * * * * cd /data/scripts && /root/.nvm/versions/node/v20.19.5/bin/node auto-gift-delivery.js $(date +\%Y-\%m-\%d) >> /data/logs/auto-gift-delivery-$(date +\%Y-\%m-\%d).log 2>&1

0 * * * * /data/scripts/backup_quantum_db.sh >> /data/logs/backup_quantum_db-$(date +\%Y-\%m-\%d).log 2>&1
# ==============================================
# 每日礼包固定时间执行
# ==============================================
# auto-payment-query.js: 每5分钟执行一次（自动查询待支付订单）
*/5 * * * * cd /data/scripts && /root/.nvm/versions/node/v20.19.5/bin/node auto-payment-query.js >> /data/logs/auto-payment-query-$(date +\%Y-\%m-\%d).log 2>&1


25 4 * * *  /www/server/cron/3ab48c27ec99cb9787749c362afae517 >> /www/server/cron/3ab48c27ec99cb9787749c362afae517.log 2>&1





